### ISSUE TITLE
unable to download test bag files

### ISSUE THREAD

**Issue by aaravrav142** [daobilige-su/loam_velodyne#3]
Hi, 

The links for the bag files are not working or has been removed. Can you point to the right link for downloading the dataset (bag files). 

Thanks
Alex

**Comment by robodhruv** [comment]
I was here to raise the same issue. It's just that the links are broken because they were not referenced correctly in the readme. You can find these, and other bags [here](http://www.frc.ri.cmu.edu/~jizhang03/Datasets/).
